### ISSUE TITLE
Wow 

### ISSUE THREAD

**Issue by toyotabedzrock** [tpetazzoni/fwupgrade#1]
Was it your intention to make a user friendly way to exploit devices remotely? I really hope no one ever added this into their firmware but given the past few years of embedded  Linux security fails it wouldn't surprise me.

Perhaps you should add some encryption and user authentication that is required before a remote flash.

**Comment by tpetazzoni** [comment]
I think you should probably tone down a bit your comments/issues when you have no idea what the original intent/usage was.

That being said, this fwupgrade tool is being used in a product, and is used being HTTP authentication. I.e, there is no way to submit a new firmware image through the CGI without having the appropriate HTTP credentials.

On the other hand, having encryption and/or authentication built into the tool would probably be interesting, so don't hesitate to submit patches. It would also be good to have some review of the code base, since there's quite a bit of string/text parsing and I haven't reviewed it from a security point of view.
